<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>FMTClient</AssemblyName>
    <Product>FMT 飛貓科技 VPN 客戶端</Product>
    <Title>FMT 飛貓科技 VPN 客戶端</Title>
    <Company>FMT</Company>
    <Description>FMT 飛貓科技 VPN 客戶端</Description>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0</InformationalVersion>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
    <ApplicationIcon>Assets\fmt-client.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\fmt-client.png" LogicalName="FMTClient.Assets.fmt-client.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>
</Project>
